### ISSUE TITLE
Stopped working!

### ISSUE THREAD

**Issue by stephenrs6** [GhostBC/classic-gold-tracker#1]
Add-on has stopped tracking gold as of 12/31/19, does not track anything in 2020.

**Comment by GhostBC** [comment]
Could you elaborate? a detailed description might helpful.

**Comment by stephenrs6** [comment]
![WoWScrnShot_021220_211808](https://user-images.githubusercontent.com/30634634/74403895-b2bc0880-4ddd-11ea-8195-a5016abb3c3d.jpg)

Does this help? Please let me know if you need more details.

**Comment by CeleBL** [comment]
I've had the same issue, I was about to uninstall/delete the addon, but thought i'd have a quick check online to see if it was still being supported.

As of right now "Today" is on page 4/7, under the day I first installed the addon.
![image](https://user-images.githubusercontent.com/11537207/74594034-a88e4a00-5029-11ea-9697-7700cc37bf15.png)

**Comment by CeleBL** [comment]
And below are pages 1/7 and 7/7 incase that helps with how it's being handled by the addon.
![image](https://user-images.githubusercontent.com/11537207/74594076-18043980-502a-11ea-9eef-a8120c77e50a.png)

**Comment by GhostBC** [comment]
Thanks for the information. I will try and have a look into this. Currently i dont have any subscription going so this might be an issue.

**Comment by nirran** [comment]
this may possibly be corrected wiht latest git entry

**Comment by GhostBC** [comment]
Marked as fixed as of version 1.2
